### ISSUE TITLE
Visitor, Nav Bar features

### ISSUE THREAD

**Issue by EricLarson2020** [sagemlee/obituary_hub#13]
As a visitor when I visit the root path/home page, I see a nav bar with a with buttons of different topics, a search bar, with an advanced search icon next to it, a login button, a register button, and a description in the middle of the page on how to use the site

**Comment by stellakunzang** [comment]
I've got all this built and tested, except for the description of how to use the site. Thinking this is something that we can come back to later once we have added more functionality and can offer more accurate instructions.

**Comment by stellakunzang** [comment]
Going to close this issue and then add a separate one regarding writing copy for the website homepage!
